/*
-- Query: SELECT * FROM fansite.fansite
LIMIT 0, 1000

-- Date: 2018-05-13 19:46
*/
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('Always Beautiful (언제나 아름다워)','@always0329','https://twitter.com/always0329','14/02','http://irene329.kr/','-','-','Always Beautiful','https://www.youtube.com/channel/UCsTBcSXeR6gDW7_NuyjCWNQ','-','-','-','-','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('B-329','@329_91','https://twitter.com/B329_91','15/12','http://b-329.tistory.com/','-','-','B329 planet','https://www.youtube.com/channel/UCRhAazTNQKQ_JMPnSOnBTAA','-','-','-','-','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('Baby Bottle','@babybottle329','https://twitter.com/babybottle329','17/10','-','-','-','-','-','-','-','-','-','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('BAEBY','@Baeby329','https://twitter.com/Baeby329','15/05','http://baeby329.tistory.com/','-','-','baeby329','https://www.youtube.com/channel/UCOMRH82s2q2CsZOLwA5fKCA','-','-','baeby329','https://www.instagram.com/baeby329/','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('Be My Brownie','@bemybrownie91','https://twitter.com/bemybrownie91','14/08','http://baejuhyun.kr/','bemybrownie91','https://www.weibo.com/bemybrownie91','Be My Brownie','https://www.youtube.com/channel/UCaBqNI3dypDhmQS_5ONfMDA','-','-','bemybrownie91','https://www.instagram.com/bemybrownie91/','unknown');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('CandyFloss (켄디프로스)','@0305candyfloss','https://twitter.com/0305candyfloss','18/01','-','-','-','-','-','-','-','-','-','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('Celestial (셀레스티얼)','@Celestial329','https://twitter.com/Celestial329','17/12','http://19910329.com/','-','-','셀레스티얼아이린','https://www.youtube.com/channel/UC4nfEKAaGFXsJxbKMpYjQsw','-','-','-','-','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('Golden Slumber','@GoldenSlumber91','https://twitter.com/GoldenSlumber91','17/08','http://goldenslumber91.tistory.com/','-','-','Golden Slumber','https://www.youtube.com/channel/UCpoV4Ha-TIJRUyFBKQrCUwQ','-','-','-','-','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('IreneBar','@IreneBar_','https://twitter.com/IreneBar_','14/11','-','Irene吧_IreneBar','https://weibo.com/BaiDuIreneBar','-','-','-','-','-','-','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('KimYerimBar','@ChinaYeriBar','https://twitter.com/ChinaYeriBar','18/01','-','金艺琳吧_KimYerimBar','https://www.weibo.com/KimyerimBar','-','-','-','-','-','-','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('Love is in the Air','@loveis329','https://twitter.com/loveis329','17/10','http://loveis329.tistory.com/','-','','Love is in the Air','https://www.youtube.com/channel/UCCPZOyLEqNKp-q4ZFCfEcFg','-','-','-','-','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('MORNING','@Morning_329','https://twitter.com/Morning_329','17/05','-','-','-','-','-','Moning','https://vimeo.com/user60159741','-','-','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('Rabbit Queen (래빗퀸)','@RabbitQueen91','https://twitter.com/RabbitQueen91','17/05','-','-','-','-','-','-','-','-','-','rest');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('Red Moon','@Red_Moon_RV','https://twitter.com/Red_Moon_RV','17/01','-','-','-','-','-','-','-','-','-','unknown');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('Snowy329','@Snowy3291','https://twitter.com/Snowy3291','18/01','-','-','-','-','-','-','-','-','-','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('Sour Candy Rabbit','@sourcandyrabbit','https://twitter.com/sourcandyrabbit','17/12','-','-','-','-','-','-','-','-','-','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('Star Blanket (별을 덮고 자는 소녀)','@starblanket_91','https://twitter.com/starblanket_91','15/11','http://starblanket.tistory.com/','-','-','별담요','https://www.youtube.com/channel/UCbQB_HxtLh7fzz1eNfTI7eg','-','-','-','-','unknown');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('SWEET CAKE','@sweetcake329','https://twitter.com/sweetcake329','12/12','http://sweetcake329.tistory.com/','-','-','SWEET CAKE','https://www.youtube.com/channel/UCiIXG670ORwMMD8or1G8-Cg','-','-','-','-','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('SweetBae','@SweetBae329','https://twitter.com/SweetBae329','17/01','http://sweetcake329.tistory.com/','SweetBae329','https://weibo.com/sweetbae329','SWEET CAKE','https://www.youtube.com/channel/UCiIXG670ORwMMD8or1G8-Cg','-','-','-','-','active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('ThinkB','@thinkB329','https://twitter.com/thinkB329','14/11','http://baejuhyun.net/','-','-','ThinkB','https://www.youtube.com/channel/UCcEx2LbkbOJ4cLqWUPZlV3g','-','-','thinkb329','https://www.instagram.com/thinkb329/','Active');
INSERT INTO `fansite` (`fName`,`twitterAccount`,`twitterLink`,`twitterStartMY`,`websiteLink`,`weiboName`,`weiboLink`,`youtubeName`,`youtubeLink`,`vimeoName`,`vimeoLink`,`igName`,`igLink`,`fStatus`) VALUES ('Ursa Major','@UMa940210','https://twitter.com/UMa940210','18/03','-','-','-','-','-','-','-','-','-','active');
